import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import Header from '../components/Header'
import Footer from '../components/Footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>ConvertKaro.com</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header code Navbar */}
      <Header />

      {/* Content  */}
      <section className="text-gray-400 body-font bg-gray-900">
        <div className="container px-5 py-24 mx-auto">
          <div className="flex flex-wrap w-full mb-20">
            <div className="lg:w-1/2 w-full mb-6 lg:mb-0">
              <h1 className="sm:text-3xl text-2xl font-medium title-font mb-2 text-white">Think Converting , Try ConvertKaro !!!</h1>
              <div className="h-1 w-60 bg-indigo-500 rounded"></div>
            </div>
            <p className="lg:w-1/2 w-full leading-relaxed text-gray-300 ">Over the years, I have seen how difficult it can be to work with files in different formats, especially when you are dealing with large amounts of data. So I decided to create this tool  to help people like you simplify the process of converting files, so you can focus on what really matters...</p>
          </div>
          <div className="flex flex-wrap -m-4">
            <div className="xl:w-1/4 md:w-1/2 p-4">
              <Link href='/ImgConvert'>
                <div className="bg-gray-800 bg-opacity-40 p-6 rounded-lg">
                  <img className="h-40 rounded w-full object-cover object-center mb-6" src="/ImageConvertor1.jpg" alt="content" />
                  <h2 className="text-lg text-center text-white font-medium title-font mb-4">Image Type Convertor</h2>
                  <p className="leading-relaxed text-base">Convert you images to different file formats, Ex- JPEG,PNG,WEBP.</p>
                </div>
              </Link>
            </div>

            <div className="xl:w-1/4 md:w-1/2 p-4">
              <Link href='/ImgToText'>
                <div className="bg-gray-800 bg-opacity-40 p-6 rounded-lg">
                  <img className="h-40 rounded w-full object-cover object-center mb-6" src="/imageText.png" alt="content" />
                  <h2 className="text-lg text-center text-white font-medium title-font mb-4">Image to Text Convertor</h2>
                  <p className="leading-relaxed text-base">Got an Image with text? Here is our tool for extracting the text from the Image</p>
                </div>
              </Link>
            </div>
            <div className="xl:w-1/4 md:w-1/2 p-4">
              <Link href='/Compress'>
                <div className="bg-gray-800 bg-opacity-40 p-6 rounded-lg">
                  <img className="h-40 rounded w-full object-cover object-center mb-6" src="/compress.png" alt="content" />
                  <h2 className="text-lg text-center text-white font-medium title-font mb-4">Image Compressor</h2>
                  <p className="leading-relaxed text-base">Compress huge size images to your own specific size. Handy when target website has uploading constraints.</p>
                </div>
              </Link>
            </div>
            <div className="xl:w-1/4 md:w-1/2 p-4">
              <Link href='/DocEncDec'>
                <div className="bg-gray-800 bg-opacity-40 p-6 rounded-lg">
                  <img className="h-40 rounded w-full object-cover object-center mb-6" src="/locker.png" alt="content" />
                  <h2 className="text-lg text-center text-white font-medium title-font mb-4">Document Locker / Unlocker</h2>
                  <p className="leading-relaxed text-base">Usefull when you want to password protect a file or remove from it</p>
                </div>
              </Link>
            </div>

          </div>
        </div>
      </section >

      {/* Footer Code below */}
      <Footer />
    </>
  )
}
